### ISSUE TITLE
Enhancement add previously learned companions

### ISSUE THREAD

**Issue by Logandros** [tkn963/mod-accountbound#2]
Any plans in the future to add the ability or script to populate account_bound_companions with already owned companions? Working well but only with new pets.

TIA!

**Comment by noisiver** [comment]
It could be done but that would mean scanning through all the players learned spells when they log in. I don't know how comfortable I would be to have that happen every time but I will think about it. I can make it so the database is only queried when there is a list of companions and mounts ready but we'll see.

**Comment by noisiver** [comment]
If I add it I'll be sure to add a config option to.. I would say reduce the potential performance hit but there really wouldn't be, to be able to turn it on (off by default).

**Comment by Logandros** [comment]
Great news, thank you for your time and work, looking forward to it.
